app/blueprints/web.py
from boto3.dynamodb.conditions import Key, Attr
from botocore.exceptions import ClientError
from uuid import uuid4
from flask import Blueprint, flash, render_template, redirect, url_for, request, session, jsonify
import app.key_config as keys
import boto3
import logging
from app.s3_upload import upload_to_s3

home_bp = Blueprint("web", __name__)

dynamodb = boto3.resource('dynamodb',
                          region_name=keys.AWS_DEFAULT_REGION,
                          aws_access_key_id=keys.AWS_ACCESS_KEY_ID,
                          aws_secret_access_key=keys.AWS_SECRET_ACCESS_KEY,
                          )


@home_bp.route('/home/<username>')
def home(username):
    user_has_listings = has_listings(username)
    return render_template("pages/home.html", username=username, has_listings=user_has_listings)


@home_bp.route('/logout')
def logout():
    session.pop('username', None)  # Remove the user's session data
    flash('You have been logged out.', 'success')
    return redirect(url_for('auth.login'))


@home_bp.route('/create_listing', methods=['GET', 'POST'])
def create_listing():
    if request.method == 'POST':
        # Retrieve form data
        description = request.form['description']
        category = request.form['category']
        condition = request.form['condition']
        size = request.form['size']
        free_shipping = 'free_shipping' in request.form
        price = request.form['price']

        # Generate a unique product ID using uuid
        product_id = str(uuid4())

        table = dynamodb.Table('products')

        # Ensure the user is logged in
        if 'username' not in session:
            flash('Please login first.', 'error')
            return redirect(url_for('auth.login'))

        # Process and upload images to S3
        uploaded_image_urls = []
        for file in request.files.getlist('photos'):
            if file.filename:
                # Upload the image to S3
                upload_result = upload_to_s3(
                    file, 'your-s3-bucket', session['username'], product_id)
                if upload_result:
                    uploaded_image_urls.append(upload_result['url'])

        # Add the new product to the table
        try:
            table.put_item(
                Item={
                    'product_id': product_id,
                    'username': session['username'],
                    'description': description,
                    'category': category,
                    'condition': condition,
                    'size': size,
                    'free_shipping': free_shipping,
                    'price': price,
                    'images': uploaded_image_urls  # Store the image URLs in DynamoDB
                }
            )
            flash('Item listed successfully!', 'success')
            products = get_user_products(session['username'])
            return render_template("pages/listings.html", username=session['username'], products=products)
        except ClientError as e:
            logging.error(e)
            flash('Error listing item. Please try again later.', 'error')
            return render_template("pages/create_listing.html")

    return render_template("pages/create_listing.html")


@home_bp.route('/listings/<username>')
def listings(username):
    if 'username' not in session or session['username'] != username:
        flash('Unauthorized access.', 'error')
        return redirect(url_for('auth.login'))

    products = get_user_products(username)
    return render_template("pages/listings.html", username=username, products=products)


@home_bp.route('/update_listing/<product_id>', methods=['POST'])
def update_listing(product_id):

    # Retrieve the form data
    edit_description = request.form['edit-description']
    edit_category = request.form['edit-category']
    edit_condition = request.form['edit-condition']
    edit_free_shipping = request.form.get('edit-free-shipping') == 'on'
    edit_size = request.form['edit-size']
    edit_price = int(request.form['edit-price'])

    # Get the DynamoDB table
    table = dynamodb.Table('products')

    # Update the item in the table
    try:
        response = table.update_item(
            Key={
                'product_id': product_id
            },
            # Include #sz for size
            UpdateExpression="set #desc = :desc, #cat = :cat, #cond = :cond, #ship = :ship, #sz = :size, #prc = :price",
            ExpressionAttributeNames={
                "#desc": "description",
                "#cat": "category",
                "#cond": "condition",
                "#ship": "free_shipping",
                "#sz": "size",
                "#prc": "price"
            },
            ExpressionAttributeValues={
                ':desc': edit_description,
                ':cat': edit_category,
                ':cond': edit_condition,
                ':ship': edit_free_shipping,
                ':size': edit_size,
                ':price': edit_price
            },
            ReturnValues="ALL_NEW"
        )

        flash('Listing updated successfully!', 'success')
        return redirect(url_for('web.listings', username=session['username']))
    except ClientError as e:
        print(f"Error: {e}")
        flash('Error updating listing. Please try again later.', 'error')
        return redirect(url_for('web.listings', username=session['username']))

# Create a route to delete a listing


@home_bp.route('/delete_listing/<string:product_id>', methods=['POST'])
def delete_listing(product_id):
    try:
        # Delete the listing from DynamoDB
        table = dynamodb.Table('products')
        response = table.delete_item(
            Key={'product_id': product_id}
        )

        # Check if the delete request was successful
        if response.get('ResponseMetadata', {}).get('HTTPStatusCode') == 200:
            return jsonify({'success': True})
        else:
            return jsonify({'success': False, 'message': 'Error deleting listing'})

    except ClientError as e:
        return jsonify({'success': False, 'message': 'Error deleting listing'})

    return jsonify({'success': False, 'message': 'Unknown error'})


@home_bp.route('/about')
def about():
    return render_template("pages/about.html")


def has_listings(username):
    table = dynamodb.Table('products')

    response = table.scan(
        FilterExpression=Attr('username').eq(username)
    )

    # Check if any items were returned
    return 'Items' in response and len(response['Items']) > 0


def get_user_products(username):
    table = dynamodb.Table('products')

    response = table.scan(
        FilterExpression=Attr('username').eq(username)
    )

    # Return the items if they exist; otherwise, return an empty list
    return response.get('Items', [])


def get_user_products(username):
    table = dynamodb.Table('products')

    response = table.scan(
        FilterExpression=Attr('username').eq(username)
    )

    # Return the items if they exist; otherwise, return an empty list
    return response.get('Items', [])

app/templates/components/footer.html
<footer>
    <p>&copy; 2023 Cherie</p>
    <p>
        <a href="#">Home</a>
        <a href="#">About</a>
        <a href="#">Services</a>
        <a href="#">Contact</a>
    </p>
</footer>

app/templates/components/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple HTML Template</title>

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">

    <!--Bootstrap JS-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

    <script src="https://apis.google.com/js/platform.js"></script>


    <link rel="stylesheet" href="../../static/style.css">

    <script>
        window.addEventListener("scroll", function () {
            var navbar = document.querySelector("nav");
            if (window.scrollY > 50) {
                navbar.classList.add("solid");
            } else {
                navbar.classList.remove("solid");
            }
        });
    </script>
</head>





<body>
    {% include 'components/signin_modal.html' %}
    {% block content %}
    <!-- Content of other pages will be inserted here -->
    {% endblock %}

</body>
<footer class="mt-5 bg-dark text-white py-4">
    <div class="container">
        <div class="row justify-content-between align-items-center">
            <div class="col-md-8 text-center">
                <a href="#" class="text-white mr-3">Home</a>
                <a href="#" class="text-white mr-3">Shop</a>
                <a href="#" class="text-white mr-3">Categories</a>
                <a href="#" class="text-white">My Account</a>
                <a href="#" class="text-white mr-3">Privacy</a>
                <a href="#" class="text-white mr-3">Terms</a>
                <a href="#" class="text-white mr-3">Safety</a>
                <a href="#" class="text-white mr-3">Sitemap</a>
                <a href="#" class="text-white">Cookies</a>
            </div>
            <div class="col-md-4 text-center">
                <a href="#" class="text-white social-icon mr-3"><i class="fab fa-facebook-f"></i></a>
                <a href="#" class="text-white social-icon mr-3"><i class="fab fa-twitter"></i></a>
                <a href="#" class="text-white social-icon"><i class="fab fa-instagram"></i></a>
            </div>
        </div>
        <hr class="mt-4">
        <div class="row">
            <div class="col-md-12 text-center">
                <p>&copy; 2023 Cherie</p>
            </div>
        </div>
    </div>
</footer>





</html>

app/templates/components/navbar.html
<link rel="stylesheet" href="../../static/css/navbar-style.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

<nav class="transparent">
    <div class="wrapper">
        <div class="logo"><a href="{{ url_for('web.home', username=session['username']) }}"><img id="navbar-logo"
                    src="../../static/img/cherie-logo.png" alt="Cherie Icon"></a></div>
        <input type="radio" name="slider" id="menu-btn">
        <input type="radio" name="slider" id="close-btn">
        <ul class="nav-links">
            <label for="close-btn" class="btn close-btn"><i class="fas fa-times"></i></label>

            <!-- Listings -->
            <li><a href="{{ url_for('web.listings', username=session['username']) }}">Listings</a></li>

            <!-- About -->
            <li><a href="#">About</a></li>

            <!-- User's dropdown with their username -->
            <li>
                <a href="#" class="desktop-item">Profile</a>
                <input type="checkbox" id="showUser">
                <label for="showUser" class="mobile-item">Username</label>
                <ul class="drop-menu">
                    <li><a href="#">Account</a></li>
                    <li><a href="{{ url_for('web.logout') }}">Logout</a></li>
                </ul>
            </li>

        </ul>
        <label for="menu-btn" class="btn menu-btn"><i class="fas fa-bars"></i></label>
    </div>
</nav>


<script>
    document.addEventListener("DOMContentLoaded", function () {
        const nav = document.querySelector("nav");
        const header = document.querySelector("#header");

        window.addEventListener("scroll", function () {
            if (window.scrollY > header.offsetHeight) {
                nav.style.background = "#242526"; // Change to your desired solid background color
            } else {
                nav.style.background = "transparent";
            }
        });
    });
</script>

app/templates/components/navbar_alt.html
<link rel="stylesheet" href="../../static/css/navbar-style.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

<nav id="header">
    <div class="wrapper">
        <div class="logo"><a href="{{ url_for('web.home', username=session['username']) }}"><img id="navbar-logo"
                    src="../../static/img/cherie-logo.png" alt="Cherie Icon"></a></div>
        <input type="radio" name="slider" id="menu-btn">
        <input type="radio" name="slider" id="close-btn">
        <ul class="nav-links">
            <label for="close-btn" class="btn close-btn"><i class="fas fa-times"></i></label>

            <!-- Listings -->
            <li><a href="{{ url_for('web.listings', username=session['username']) }}">Listings</a></li>

            <!-- About -->
            <li><a href="#">About</a></li>

            <!-- User's dropdown with their username -->
            <li>
                <a href="#" class="desktop-item">Profile</a>
                <input type="checkbox" id="showUser">
                <label for="showUser" class="mobile-item">Username</label>
                <ul class="drop-menu">
                    <li><a href="#">Account</a></li>
                    <li><a href="{{ url_for('web.logout') }}">Logout</a></li>
                </ul>
            </li>

        </ul>
        <label for="menu-btn" class="btn menu-btn"><i class="fas fa-bars"></i></label>
    </div>
</nav>

app/templates/components/signin_modal.html
<!-- Sign In/Register Modal -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

<div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="signInModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="signInModalLabel">Sign In/Register</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Sign in with Cherie -->
                <a href="{{url_for('auth.login')}}">
                    <button class="btn btn-primary btn-block">Sign in with Cherie</button>
                </a>

                <!-- Sign in with Google -->
                <button class="btn btn-danger btn-block">Sign in with Google</button>

                <!-- Divider -->
                <hr>

                <!-- Create your Cherie account -->
                <a href="{{url_for('auth.register')}}">
                    <button class="btn btn-secondary btn-block">Create your Cherie account</button>
                </a>
            </div>
        </div>
    </div>
</div>